BLOCKS-155: created loading animation for lazy loading of sceneobjects
Catrobat/Catblocks pull request #179
Opened 2020-08-17 09:29 UTC by patlov

created a loading animation for the lazy loading of sceneobjects, now a loading modal gets popped when you click on a scene the first time

### Your checklist for this pull request
- [X] Include the name of the Jira ticket in the PR’s title
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [X] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Make sure you use BLOCKS instead of CATROID in your commit message
- [X] Stick to the project’s gitflow workflow
- [X] Verify that your changes do not have any conflicts with the base branch
- [X] After the PR, verify that all CI checks have passed (Actions)
- [X] Post a message in the *#catblocks* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-01 09:17 UTC, bprattes approved these changes
LGTM

2020-09-02 18:41 UTC, MichaelFlucher requested changes
I made a little Benchmark with the Binding of Krishna opening all scenes from bottom to top. Without the animation it took me 25 seconds, with animations 51 seconds.

2020-09-06 14:53 UTC, bprattes approved these changes
LGTM

2020-09-11 09:10 UTC, MichaelFlucher approved these changes
I don't know what you have changed but it is way better now, well done!

2020-09-11 09:13 UTC, merged