BLOCKS-272 Create more Catblocks tests
Catrobat/Catblocks pull request #317
Opened 2021-11-17 18:27 UTC by MozartPanda

Added new parser test cases.
https://jira.catrob.at/browse/BLOCKS-272

### Your checklist for this pull request
- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Make sure you use BLOCKS instead of CATROID in your commit message
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed (Actions)
- [x] Post a message in the *#catblocks* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-11-24 16:36 UTC, liflyanna approved these changes
LGTM

2021-11-29 17:25 UTC, bprattes requested changes

2021-11-29 17:25 UTC, bprattes commented on test/jsunit/parser/parser.test.js
> +    test('multiple formular', async () => {
please fix typo: formula instead of formular

2021-11-29 17:25 UTC, bprattes commented on test/jsunit/parser/parser.test.js
> +    test('formular with 3 arguments', async () => {
please fix typo: formula instead of formular

2021-11-29 17:25 UTC, bprattes commented on test/jsunit/parser/parser.test.js
> +          <programName>formulars</programName>
please fix typo: formula instead of formular

2021-12-14 18:59 UTC, bprattes approved these changes
LGTM

2021-12-15 16:32 UTC, merged